### ISSUE TITLE
trouble building HEIR: timeout running `git reset`

### ISSUE THREAD

**Issue by johnmatter** [google/heir#718]
Hello

I am trying to build HEIR following the [Getting Started](https://heir.dev/docs/getting_started/) docs.

This is on a university Intel Xeon cluster running Rocky Linux. I'm using bazel 7.1.2.

Happy to reply with other env/hardware if needed. Thanks!

```
jmatter heir $ bazel build @heir//tools:heir-opt
WARNING: Output base '/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server (1765298) after 10 seconds ...
INFO: Repository llvm-raw instantiated at:
  /home/jmatter/heir/WORKSPACE:43:12: in <toplevel>
  /home/jmatter/heir/bazel/import_llvm.bzl:12:23: in import_llvm
Repository rule git_repository defined at:
  /home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 110, column 10, in _update
		reset(ctx, git_repo)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 155, column 9, in reset
		_git(ctx, git_repo, "reset", "--hard", git_repo.reset_ref)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git reset --hard 392ca64893dc77f823cb4734238f1ba1d271b997' while working with @llvm-raw:
Timed out
ERROR: /home/jmatter/heir/WORKSPACE:43:12: fetching git_repository rule //external:llvm-raw: Traceback (most recent call last):
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 110, column 10, in _update
		reset(ctx, git_repo)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 155, column 9, in reset
		_git(ctx, git_repo, "reset", "--hard", git_repo.reset_ref)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git reset --hard 392ca64893dc77f823cb4734238f1ba1d271b997' while working with @llvm-raw:
Timed out
ERROR: Error computing the main repository mapping: no such package '@llvm-raw//utils/bazel': error running 'git reset --hard 392ca64893dc77f823cb4734238f1ba1d271b997' while working with @llvm-raw:
Timed out
Loading:
jmatter heir $
```

**Comment by asraa** [comment]
Hey! Do you know if it's because git itself on your machine is timing out? (see https://groups.google.com/g/bazel-discuss/c/XQpMONOIHsQ)

It seems like you might be able to increase that timeout (https://github.com/bazelbuild/bazel/issues/6029) as well. Could you check to see if running `bazel clean --expunge` and then retrying might work?

If not, I think we could add [shallow_since](https://bazel.build/rules/lib/repo/git#new_git_repository-shallow_since) to our [new_git_repository](https://github.com/google/heir/blob/main/bazel/import_llvm.bzl#L12C5-L12C23) and maybe that saves some time? But I'm not totally sure it will or that it's a good idea, since bazel says it is buggy

**Comment by j2kun** [comment]
> WARNING: Output base
'/home/jmatter/.cache/bazel/_bazel_jmatter/261dd8aa36a61e57ee04e376d53b37d9'
is on NFS. This may lead to surprising failures and undetermined behavior.

This seems like a suspicious warning.

Try the output_base flag and cf the note about NFS here:
https://bazel.build/docs/user-manual#output-base

**Comment by johnmatter** [comment]
> Try the output_base flag and cf the note about NFS here: https://bazel.build/docs/user-manual#output-base
I'm also new to bazel so thanks for the tip! I'm not sure what other filesystems I have access to—I'll talk to our IT folks.

**Comment by johnmatter** [comment]
For some reason, I stopped getting a timeout error! It's failing now with `gcc: error trying to exec 'cc1': execvp: No such file or directory`. I think that's just a bazel/environment thing so I won't take up your time troubleshooting that :)

For future reference (mine and others') bazel apparently has a flag that might help with this kind of thing:
```
--experimental_scale_timeouts=<a double> default: "1.0"
Scale all timeouts in Starlark repository rules by this factor. In this way, external repositories can be made working on machines that are slower than the rule author expected, without changing the source code
```
\- [Command-Line Reference | Bazel](https://bazel.build/reference/command-line-reference#flag--experimental_scale_timeouts)

**Comment by asraa** [comment]
Hey! Just looking at that last error coming from `gcc`, we normally build with `clang`, so to change that you can set your `CC` and `CXX` env vars to clang/clang++. That being said normally I can build with gcc too so it might just be a missing package
